apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-share-pvc
  labels:
    app: jira-share-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
